// Para lógica interna (no cambiar)
export const ORDER_STATUS = {
  PENDING: "PENDING",
  RECEIVED: "RECEIVED", 
  PREPARING: "PREPARING",
  COOKING: "COOKING",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  WITH_DRIVER: "WITH_DRIVER",
  ON_THE_WAY: "ON_THE_WAY",
  DELIVERED: "DELIVERED"
};

export const ORDER_STEPS = [
  ORDER_STATUS.PENDING,
  ORDER_STATUS.RECEIVED,
  ORDER_STATUS.PREPARING,
  ORDER_STATUS.COOKING, 
  ORDER_STATUS.OUT_FOR_DELIVERY,
  ORDER_STATUS.WITH_DRIVER,
  ORDER_STATUS.ON_THE_WAY,
  ORDER_STATUS.DELIVERED
];

// Para mostrar al usuario (en español)
export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.PENDING]: "Pendiente",
  [ORDER_STATUS.RECEIVED]: "Recibido",
  [ORDER_STATUS.PREPARING]: "Preparando",
  [ORDER_STATUS.COOKING]: "Cocinando",
  [ORDER_STATUS.OUT_FOR_DELIVERY]: "Despachado", 
  [ORDER_STATUS.WITH_DRIVER]: "Con repartidor",
  [ORDER_STATUS.ON_THE_WAY]: "En camino",
  [ORDER_STATUS.DELIVERED]: "Entregado"
};